/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/navigation/Breadcrumb.vue')['default']
    ChartCard: typeof import('./components/ChartCard.vue')['default']
    ConditionBuilder: typeof import('./components/SearchForm/ConditionBuilder.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderNav: typeof import('./components/header/HeaderNav.vue')['default']
    ModuleSelector: typeof import('./components/navigation/ModuleSelector.vue')['default']
    NavMenu: typeof import('./components/navigation/NavMenu.vue')['default']
    OrderItemsTable: typeof import('./components/OrderItemsTable.vue')['default']
    OrderStatusFlow: typeof import('./components/OrderStatusFlow.vue')['default']
    OrderStatusProgress: typeof import('./components/OrderStatusProgress.vue')['default']
    OrderStatusTag: typeof import('./components/OrderStatusTag.vue')['default']
    PackagesTable: typeof import('./components/PackagesTable.vue')['default']
    PriceRangeInput: typeof import('./components/SearchForm/PriceRangeInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/SearchForm/index.vue')['default']
    StatusTag: typeof import('./components/StatusTag/index.vue')['default']
    TriggerConditions: typeof import('./components/SearchForm/TriggerConditions.vue')['default']
    UserInfo: typeof import('./components/navigation/UserInfo.vue')['default']
  }
}
